const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const context = { window: {} };
vm.runInNewContext(fs.readFileSync(path.join(__dirname, '../src/audio_visual/renderer3d.js'), 'utf8'), context);
const picker = Object.create(context.window.Defence3Renderer3D.prototype);
picker.cssWidth = picker.cssHeight = 100;
picker.pickInverseViewProjection = [1,0,0,0, 0,1,0,0, 0,0,1,0, 0,0,0,1];
const mesh = { positions: [-.5,0,0, .5,0,0, 0,1,0], indices: [0,1,2], bounds: [-.5,0,0,.5,1,0] };
function object(source, extra = {}, shape = mesh) {
    return { object: { pickSource: source, x: 0, y: 0, z: 0, scaleX: 1, scaleY: 1, scaleZ: 1, rotationY: 0, ...extra }, mesh: shape };
}
const unit = {}, building = {};
const candidates = new Map([[unit, {}], [building, {}]]);
const pick = (x, y) => picker.pickRenderedSource(x, y, candidates);
picker.pickObjects = [object(unit)];
assert.equal(pick(50, 10), unit, 'head hits the triangle');
assert.equal(pick(72, 10), null, 'empty corner inside bounding box must miss');
picker.pickObjects = [object(building, { scaleY: .2 })];
assert.equal(pick(50, 10), null, 'squashed building cannot intercept clicks at its old height');
assert.equal(pick(50, 45), building, 'flattened surface remains selectable');
picker.pickObjects = [object(building, { z: .3 }), object(unit, { z: -.3 })];
assert.equal(pick(50, 30), unit, 'nearest surface wins regardless of candidate order');
picker.pickObjects.reverse();
assert.equal(pick(50, 30), unit);
picker.pickObjects = [object(unit, { x: -.5 }), object(building, { x: .5 })];
assert.equal(pick(25, 30), unit);
assert.equal(pick(75, 30), building);
const animatedMesh = { ...mesh, details: [0,0,0,0, 0,0,0,0, 0,0,0,0] };
picker.pickObjects = [object(unit, { animationMode: 5, walkPhase: 0 }, animatedMesh)];
assert.equal(pick(50, 0), unit, 'animated vertices follow the shader pose');
picker.pickObjects = [object(unit, { z: 2 })];
assert.equal(pick(50, 30), null, 'beyond far clip plane is excluded');
const panelMesh = { ...mesh, details: [4,0,0,0, 4,0,0,0, 4,0,0,0], uvs: [0,0,1,0,.5,1] };
let alpha = 0;
const canvas = { width: 1, height: 1, getContext: () => ({ getImageData: () => ({ width: 1, height: 1, data: [255,255,255,alpha] }) }) };
picker.pickObjects = [object(unit, { topTextureCanvas: canvas }, panelMesh)];
assert.equal(pick(50, 30), null, 'transparent panel pixels are not clickable');
alpha = 255;
assert.equal(pick(50, 30), unit, 'opaque panel pixels are clickable');
console.log('PASS: mesh picking covers heads, silhouette gaps, squashing, depth, adjacent targets, animation and clipping.');
